version: '3.8'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    environment:
      - TEST_AUTH_TOKEN
    network_mode: service:redis
    command: sleep infinity

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
