name: Build
on:
  pull_request:
    branches:
      - main

jobs:
  test-net6:
    name: Test .NET 6.0
    strategy:
      matrix:
        backend: [momento, redis]
    runs-on: ubuntu-latest
    env:
      TEST_AUTH_TOKEN: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}
      TEST_CACHE_NAME: stackexchange-redis-${{ github.sha }}-net6.0
      USE_REDIS: ${{ matrix.backend == 'redis' }}

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test -f net6.0

  # Note: container services are only supported on Ubuntu, and we need to run
  # .NET Framework tests on Windows, so we cannot test Redis for the .NET Framework
  # tests.
  # That is why this is a separate job.
  test-net-framework:
    name: Test .NET Framework
    runs-on: windows-latest

    env:
      TEST_AUTH_TOKEN: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}
      TEST_CACHE_NAME: stackexchange-redis-${{ github.sha }}-net-framework

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test -f net461
