name: Build
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target-framework: net6.0
          - os: windows-latest
            target-framework: net461
    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test -f ${{ matrix.target-framework }}
